targets:
  $default:
    builders:
      # Don't clean up workshop examples, they need to be served.
      build_web_compilers:dart_source_cleanup:
        generate_for:
          exclude:
            - web/example/workshops/**.dart

      build_web_compilers|entrypoint:
        # Don't compile workshop examples.
        generate_for:
          exclude:
          - web/example/workshops/**.dart
        options:
          dart2js_args:
          - --fast-startup
          - --minify
          - --no-source-maps
          - -DSERVER_URL=http://tst.sh:8082/
          - -DSTABLE_SERVER_URL=http://tst.sh:8082/

      json_serializable:
        # Ignore workshop samples.
        generate_for:
          exclude:
          - web/example/workshops/**.dart

global_options:
  build_web_compilers:ddc:
    options:
      environment:
        SERVER_URL: http://tst.sh:8082/
        STABLE_SERVER_URL: http://tst.sh:8082/
